/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CaculateEmployeeController;
import controller.UserController;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.CaculateInterest;
import model.Customer;
import model.Loan_asset;
import model.Loan_none_asset;
import model.User;

/**
 *
 * @author nam
 */
public class JFrameCaculateEmployee extends javax.swing.JFrame {

    private ArrayList<CaculateInterest> list;
    DefaultTableModel model, model2;
    private int size = 0;
    private ArrayList<Long> MangTienGocConLai; // mảng tiền gốc còn lại sau khi trừ lãi hàng tháng 
    private ArrayList<Long> MangTienLai; // mảng tiền lãi
    private ArrayList<Long> MangTong; // mảng tổng tiền phải trả hàng tháng = tiền gốc trả hàng tháng + tiền lãi hàng tháng
    /**
     * Creates new form JFrameCaculateEmployee
     */
    public JFrameCaculateEmployee() {
        initComponents();
        this.setLocationRelativeTo(null);
        list = new ArrayList();
        // Mảng tiền gốc còn lại sau khi đã trừ tiền trả từng tháng một 
        MangTienGocConLai = new ArrayList<>();
        // Mảng tiền lãi hàng tháng 
        MangTienLai = new ArrayList<>();
        // Mảng tổng tiền phải trả hàng tháng 
        MangTong = new ArrayList<>();
        model = (DefaultTableModel) jTable1.getModel();
        model2 = (DefaultTableModel) jTable2.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbHoTen = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbSoCMTND = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbSoTienVay = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbHinhThucVay = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cbCachThuc = new javax.swing.JComboBox<>();
        lbCachThuc = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLaiXuatKiDauTien = new javax.swing.JTextField();
        txtLaiXuatChoVayNgay = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbThoiGianVay = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lbTrangThai = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbNgayBatDauVay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Thông Tin Khách Hàng Vay");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jLabel3.setText("Họ Tên:");

        lbHoTen.setText("Họ Tên");

        jLabel5.setText("Số CMTND");

        lbSoCMTND.setText("Số CMTND");

        jLabel7.setText("Số Tiền Vay");

        lbSoTienVay.setText("Số Tiền Vay");

        jLabel9.setText("Hình Thức Vay");

        cbHinhThucVay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Có tài sản đảm bảo", "Không có tài sản đảm bảo" }));
        cbHinhThucVay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHinhThucVayActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tháng", "Tiền vay còn lại", "Tiền vay trả hàng tháng", "Tiền lãi trả hàng tháng", "Tổng tiền trả hàng tháng", "Trạng thái", "Ngày thanh toán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        cbCachThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCachThucActionPerformed(evt);
            }
        });

        lbCachThuc.setText("jLabel10");

        jLabel4.setText("Lãi xuất kì đầu tiên");

        jLabel6.setText("Lãi xuất cho vay ngày");

        txtLaiXuatKiDauTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLaiXuatKiDauTienActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel2.setText("%");

        jLabel8.setText("%");

        jLabel10.setText("Thời gian vay");

        lbThoiGianVay.setText("24");

        jButton2.setText("Lưu");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Số CMTND", "Họ Tên", "Email", "Số ĐT "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        lbTrangThai.setText("Trạng Thái");

        jLabel12.setText("Ngày bắt đầu vay");

        lbNgayBatDauVay.setText("Ngày bắt đầu vay");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(lbCachThuc)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbHoTen)
                                    .addComponent(lbSoCMTND)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtLaiXuatKiDauTien, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtLaiXuatChoVayNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8))
                                    .addComponent(cbHinhThucVay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbCachThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbThoiGianVay)
                                    .addComponent(lbSoTienVay)
                                    .addComponent(lbNgayBatDauVay))
                                .addGap(95, 95, 95)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btnTimKiem)
                        .addGap(68, 68, 68)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(lbTrangThai)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem)
                    .addComponent(lbTrangThai))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbHoTen))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbSoCMTND))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbHinhThucVay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lbSoTienVay))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lbThoiGianVay))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lbNgayBatDauVay))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCachThuc)
                            .addComponent(cbCachThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtLaiXuatKiDauTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtLaiXuatChoVayNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLaiXuatKiDauTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLaiXuatKiDauTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLaiXuatKiDauTienActionPerformed

    private void cbHinhThucVayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHinhThucVayActionPerformed
        // TODO add your handling code here:
        if (cbHinhThucVay.getSelectedItem() == "Có tài sản đảm bảo") {
            cbCachThuc.removeAllItems();
            lbCachThuc.setText("Thời hạn vay");
            cbCachThuc.addItem("Ngắn hạn");
            cbCachThuc.addItem("Dài hạn");
        } else {
            cbCachThuc.removeAllItems();
            lbCachThuc.setText("Hình thức tính lãi");
            cbCachThuc.addItem("Tính theo dư nợ ban đầu");
            cbCachThuc.addItem("Tính theo dư nợ giảm dần");
        }
    }//GEN-LAST:event_cbHinhThucVayActionPerformed

    private void cbCachThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCachThucActionPerformed
        // TODO add your handling code here:
        if(cbHinhThucVay.getSelectedItem() == "Có tài sản đảm bảo" && 
                cbCachThuc.getSelectedItem() == "Ngắn hạn") {
            lbSoTienVay.setText("");
            txtLaiXuatKiDauTien.setText("9.2");
            txtLaiXuatChoVayNgay.setText("12.0");
        } 
        else if(cbHinhThucVay.getSelectedItem() == "Có tài sản đảm bảo" && 
                cbCachThuc.getSelectedItem() == "Dài hạn") {
            txtLaiXuatKiDauTien.setText("9.8");
            txtLaiXuatChoVayNgay.setText("12.5");
        }
        else if(cbHinhThucVay.getSelectedItem() == "Không có tài sản đảm bảo" && 
                cbCachThuc.getSelectedItem() == "Tính theo dư nợ ban đầu") {
            lbSoTienVay.setText("");
            txtLaiXuatKiDauTien.setText("12.0");
            txtLaiXuatChoVayNgay.setText("17.4"); 
        }
        else if(cbHinhThucVay.getSelectedItem() == "Không có tài sản đảm bảo" && 
                cbCachThuc.getSelectedItem() == "Tính theo dư nợ giảm dần") {
            txtLaiXuatKiDauTien.setText("22.0");
            txtLaiXuatChoVayNgay.setText("22.0"); 
        }
    }//GEN-LAST:event_cbCachThucActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
//        System.out.println(lbSoTienVay.getText());        cbHinhThucVay.setSelectedIndex(0);
//        lbSoTienVay.setText("");
//        lbThoiGianVay.setText("");
        model2.setRowCount(0);
        showResultSearch();

    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    public void tinhLai() {
        model.setRowCount(0);
        MangTienGocConLai.clear();
        MangTienLai.clear();
        MangTong.clear();
        long soTienVay = Long.parseLong(lbSoTienVay.getText());
        int thoiGianVay = Integer.parseInt(lbThoiGianVay.getText());
        float laiXuat = Float.parseFloat(txtLaiXuatKiDauTien.getText());

        size = thoiGianVay;

        // Số tiền gốc phải trả hàng tháng
        long soTienGocTraHangThang = (long) soTienVay / thoiGianVay;
        // lãi xuất tính trên tháng 
        float laiXuatTrenThang = (float) laiXuat / 12 / 100;
        // Số tiền lãi phải trả tháng đầu tiên 
        long tienLaiTraThangDauTien =(long) ((float)soTienVay * laiXuatTrenThang);

        long du = 0;
        for (int i = 1; i <= thoiGianVay; i++) {
            // Số tiền lãi phải trả tháng i 
            long soTienLaiHangThang = (long) ((float)soTienVay * laiXuatTrenThang);
            MangTienLai.add(soTienLaiHangThang);

            // Tổng số tiền gôc còn lại sau khi trừ số tiền gốc phải trả hàng tháng
            if(i != thoiGianVay) {
                soTienVay = (long) (soTienVay - soTienGocTraHangThang);
                // Tổng số tiền phải trả tháng i 
                long tong = (long) soTienLaiHangThang + soTienGocTraHangThang;
                MangTong.add(tong);
            } else {
                du = (long) (soTienVay - soTienGocTraHangThang);
                long tong = (long) soTienLaiHangThang + soTienGocTraHangThang + du;
                MangTong.add(tong);
                soTienVay = 0;
            }
            MangTienGocConLai.add(soTienVay);
        }

        long tong = soTienGocTraHangThang + tienLaiTraThangDauTien;

        CaculateInterest caculate = new CaculateInterest();
        caculate.setTienGocConLai(MangTienGocConLai);
        caculate.setTienLaiTraHangThang(MangTienLai);
        caculate.setGocTraHangThang(soTienGocTraHangThang);
        caculate.setTongTienTraHangThang(MangTong);
        list.add(caculate);
        showResult();
    }
    
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
// Lấy giá trị tính lãi
        int id = (int) jTable2.getValueAt(jTable2.getSelectedRow(), 0);
        User user = null;
        CaculateEmployeeController caculateEmployeeController = new CaculateEmployeeController();
        user = caculateEmployeeController.findUser(id);
        Customer customer = null;
        customer = caculateEmployeeController.findCustomerByUserId(user.getId());
//        System.out.println(user.getId());
//        System.out.println(customer.getUser_id());
//        System.out.println(customer.getId());
        if(customer != null) {
            lbTrangThai.setText("");
            Loan_asset loanAsset = null;
            loanAsset = caculateEmployeeController.findLoanAsset(customer.getId());

            Loan_none_asset loanNoneAsset = null;
            loanNoneAsset = caculateEmployeeController.findLoanNoneAsset(customer.getId());
//            System.out.println(loanNoneAsset);
            lbHoTen.setText(user.getName());
            lbSoCMTND.setText(user.getCmnd());
            
            if(loanAsset != null || loanNoneAsset != null) {
                if(loanAsset != null && cbHinhThucVay.getSelectedItem() == "Có tài sản đảm bảo") {
                    lbSoTienVay.setText((long) loanAsset.getAmount()+ "");
                }else if(loanNoneAsset != null && cbHinhThucVay.getSelectedItem() == "Không có tài sản đảm bảo") {
                    lbSoTienVay.setText((long) loanNoneAsset.getAmount()+ "");
                }
            } else {
                lbTrangThai.setText("");
                lbHoTen.setText("");
                lbSoCMTND.setText("");
                lbSoTienVay.setText("");
//                lbThoiGianVay.setText("");
                lbNgayBatDauVay.setText("");
                lbTrangThai.setText("chua co thong tin Loan Asset");
            }
            lbNgayBatDauVay.setText(loanNoneAsset.getStart_date() + "");
        } else {
            lbTrangThai.setText("Khách hàng này chưa có thông tin customer");
        }
// Tính lãi và hiển thị   
    tinhLai();

    }//GEN-LAST:event_jTable2MouseClicked
    int j = 1;

    public void showResult() {
        CaculateInterest c = list.get(0);
        for (int i = 0; i < size; i++) {
            model.addRow(new Object[]{
                i + 1, c.getTienGocConLai().get(i), c.getGocTraHangThang(), c.getTienLaiTraHangThang().get(i), c.getTongTienTraHangThang().get(i)
            });
        }
    }
    
    public void showResultSearch() {
        ArrayList<User> users = new ArrayList<>();
        users.clear();
        UserController userController = new UserController();
        users = userController.ListUsers(txtSearch.getText());
        
        if(users.size() == 0) {
            lbTrangThai.setText("Khong tim thay khach hang");
        } else {
            lbTrangThai.setText("");
        }
        
        for(int i = 0; i < users.size(); i++) {
            model2.addRow(new Object[] {
                users.get(i).getId() , users.get(i).getCmnd(), users.get(i).getName(), users.get(i).getEmail(), users.get(i).getPhone()
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCaculateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCaculateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCaculateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCaculateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCaculateEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbCachThuc;
    private javax.swing.JComboBox<String> cbHinhThucVay;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbCachThuc;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbNgayBatDauVay;
    private javax.swing.JLabel lbSoCMTND;
    private javax.swing.JLabel lbSoTienVay;
    private javax.swing.JLabel lbThoiGianVay;
    private javax.swing.JLabel lbTrangThai;
    private javax.swing.JTextField txtLaiXuatChoVayNgay;
    private javax.swing.JTextField txtLaiXuatKiDauTien;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
